### ISSUE TITLE
Error when disarming

### ISSUE THREAD

**Issue by autumnwalker** [mklips0/envisakit#2]
Hello,

When I try to run `./envisakit-cli status` it always returns "unknown". When I try to run `./envisakit-cli disarm -p ####` I get the following error:

```
Using EZMobile interface...
Detecting commands...
Detecting arm types...
Traceback (most recent call last):
  File "./envisakit.py", line 520, in <module>
    main()
  File "./envisakit.py", line 515, in main
    ma.issue(command_id, **extra_fields)
  File "./envisakit.py", line 334, in issue
    command_url = self.commandActions[command_id]
KeyError: 1
```

Thoughts?

**Comment by mklips0** [comment]
Looks like the "disarm" command wasn't correctly discovered. This should be handled nicer, I'll fix this in the code.

In the meantime, do you have anything in your ``envisalink-config.json`` file set for the properties "ignore" or "only"? If so, remove those lines completely so that your config looks like this (but with real values):

```
{
	"mobile-url": "https://www.eyez-on.com/EZMOBILE/index.php",
	"mid": "abcdefghijklmnopqrstuvwxyz01234567890000",
	"did": "000000000000",
	"partition": "1"
}
```

Then give it a try and please report back... Remember to be mindful of the comma at the end of the lines - your last configuration line should *not* have a comma, as shown above.

**Comment by autumnwalker** [comment]
I had the default line examples for "ignore" and "only" in my file, I removed them. I still get the same error:

```
Using EZMobile interface...
Detecting commands...
Detecting arm types...
Traceback (most recent call last):
  File "./envisakit.py", line 520, in <module>
    main()
  File "./envisakit.py", line 515, in main
    ma.issue(command_id, **extra_fields)
  File "./envisakit.py", line 334, in issue
    command_url = self.commandActions[command_id]
KeyError: 1
```

**Comment by mklips0** [comment]
Ok, thanks. 

It looks like the script is having trouble finding the disarm command on the EZMOBILE page. Not sure why, however...

Can you show me the output of `./envisakit-cli help`? This should list all of the commands that it found... I'd like to see if it's finding *anything* or if it's just having trouble with disarm.

**Comment by autumnwalker** [comment]
hmm ... this is telling!

```
Using EZMobile interface...
Detecting commands...
Detecting arm types...

Usage: ./envisakit.py COMMAND [-p PIN] [-c config_file] [-f key=value]

Detected commands:

* status - Gets the status of the partition
* help - Lists all possible commands
```

**Comment by mklips0** [comment]
Can you navigate to the following URL in a browser on your computer? Replace the **\<param>** placeholders below with the values that you have set in your ``envisalink-config.json``.

**\<mobile-url>**?mid=**\<mid>**&did=**\<did>**&part=**\<partition>**&action=partcommands

If you navigate to this URL, do you see a list of commands like the attached screenshot?
<img width="487" alt="screen shot 2015-12-16 at 15 29 44" src="https://cloud.githubusercontent.com/assets/1330354/11853072/de7d6a7c-a409-11e5-9518-aca7012a7f61.png">

**Comment by autumnwalker** [comment]
I see something completely different:

![partition1_commands](https://cloud.githubusercontent.com/assets/11489678/11853789/64609ec8-a416-11e5-826e-58e28b1179df.jpg)

**Comment by mklips0** [comment]
OK, that's a big problem then. What kind of panel do you have? Didn't realize that the interface was not standardized for everyone, so unfortunately it's not built to handle that type of interface. I would try and look into this, but without a panel to work with myself it's not really feasible :(

If you're looking for homekit connectivity, then you could look at the following -

If you have an Ademco/Vista panel, try configuring `envisalink-ademco-config.json` (and make sure you're at the latest commit). By doing so, `envisakit-cli` will use the TPI rather than ezmobile, which would work around this issue. This will not work on a DSC panel though.

If you have a DSC panel, I suspect that you could set up [AlarmServer](https://github.com/juggie/AlarmServer) which will give you HTTPS endpoints that arm and disarm the panel (e.g., `https://localhost:8111/api/alarm/disarm`). Then, you can use the [homebridge-http](https://github.com/rudders/homebridge-http) to set up a "switch" accessory where ON can pull the "arm" endpoint and OFF can pull the "disarm" endpoint. I have no experience with this setup personally but it would work very similarly to envisakit + homebridge-envisakit.

Hope this helps...

**Comment by autumnwalker** [comment]
Panel is DSC PC1616.

**Comment by mklips0** [comment]
Unfortunately I'm not...

Thanks for the info about the panel. I've added a warning to the README that DSC panels may not be compatible right now. If anyone submits a PR to add compatibility for DSC I'll be happy to merge it. For now I'll close the issue since I have no way on adding this compatibility myself. Sorry!
